- server/.gitignore
- server/README.md
@kazegusuri @adwd こういう気持ちでどうでしょう？
Next step:
* net/http でリクエスト受けられるようにする
* Googleログイン仮組みする
* 適当にDockerする
* GraphQLのセットアップ
> ざっくりREADMEに構成案書いた

- server/Dockerfile
- server/README.md
- server/cmd/mtcserver/main.go
- server/go.mod
Makefileは引数渡せないから嫌いだけど何でビルドしようかな…(課題
> 適当にビルドできるようにした

- web/.dockerignore
- web/Dockerfile
> Add Dockerfile

- web/containers/Top/Footer.tsx
- web/containers/Top/index.tsx
> Add Footer

- web/components/Text.tsx
intefaceの頭に `I` がついてる箇所があったので修正
> Remove `I` prefix from inteface

- .circleci/config.yml
- README.md
> CircleCIの設定追加

- .circleci/config.yml
masterブランチでもDockerイメージをアップロードするように
> deploy in master branch

- web/containers/Top/Header/HeaderPC.tsx
- web/containers/Top/Header/HeaderSP.tsx
- web/store/timetable.ts
> Merge into master

- web/static/json/contents.json
- web/store/timetable.ts
https://mercari.slack.com/archives/CACGV8VNG/p1536123695000100
Mokさんより
> For our MTC website, can you change my name as "Dr. Mok Oh"?  It usually looks more legit and will attract more potential hires.
> Update Mok Oh's name to include title

- server/.gitignore
> ぐすり案取り込み refs #113

- schema.graphql
- server/config/loader.go
- server/gqlapi/generated.go
- server/gqlapi/models_gen.go
- server/gqlapi/resolver.go
> add Session.type and Speaker.speakerId

- web/store/timetable.ts
タイムテーブルを一応訳してみる
@panpanini チェックお願いします 🙏
> translate timetable

- web/containers/Top/Header/HeaderPC.tsx
- web/containers/Top/Header/HeaderSP.tsx
- web/containers/Top/Header/LanguageToggleButton.tsx
- web/static/images/en.svg
- web/static/images/ja.svg
> add language toggle button

- web/containers/Top/TimetableSection/TimetableContentSlot.tsx
- web/containers/Top/TimetableSection/TimetableOtherSlot.tsx
- web/containers/Top/TimetableSection/TimetableRow.tsx
- web/containers/Top/TimetableSection/index.tsx
タイムテーブルのクリック機能追加しました。クリックすると詳細に飛びます。
ホバーはこんな感じ
> Add click feature to timetable

- server/README.md
> Change readme when schema changed

- web/locales/en-US/common.json
- web/locales/ja-JP/common.json
- web/pages/2018/index.tsx
@sawa-zen exhibitionsの文字列リソースこんな感じで良さそうでしょうか 👀
> Add exhibition trans resource

- web/components/styles.ts
- web/next.config.js
apollo周りでObject.assignを使用しているため、ie11でエラーが出ていました。polyfillを挟んでみたのでレビューお願いします 🙇
> Add polyfill

- server/contents/contents.json
Because Atsuko will be speaking first, I thought its better to list her first on the website too.
> Change order of Speakers for US@Tokyo team

- server/cmd/mtcserver/http_middleware.go
- server/cmd/mtcserver/main.go
> add access logger

- web/components/styles.ts
- web/layout/Default.tsx
- web/package-lock.json
- web/package.json
- web/pages/_document.tsx
Fontのlazy loadを追加してrender-blockingを解消
> Lazy load font

- web/next.config.js
- web/package-lock.json
- web/package.json
intersection observerのpolyfillを追加
> Add intersection observer polyfill

- web/containers/Top/MainVisual.tsx
> Remove ticket button

- server/cmd/mtcserver/main.go
refs https://github.com/DataDog/opencensus-go-exporter-datadog/pull/12
@kazegusuri ありがたや〜〜〜 🙏
> DataDogにGlobalTagsを設定するように変更

- server/go.mod
- server/go.sum
- server/gqlapi/generated.go
https://github.com/99designs/gqlgen/tree/feat-middleware-contains-childnodes
詳細は後で書く
> gqlgenでTraceのSpanの親子関係がいい感じになるように実験中

- server/cmd/mtcserver/main.go
#238
https://github.com/99designs/gqlgen/pull/404
> add RequestMiddleware about apollo-tracing

- server/go.mod
- server/go.sum
- server/gqlapi/generated.go
https://github.com/99designs/gqlgen/pull/419
> エラー出力が上手く行ってなかった問題を修正
